# This is a basic workflow to help you get started with Actions

name: Waka README

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: '30 18 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
     name: Update Readme with metrics
     runs-on: ubuntu-latest
     steps:
       - uses: anmols098/waka-readme-stas@master
         with:
           WAKA_TIME_API_KEY: ${{ secrets.WAKA_TIME_API_KEY }}
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
           SHOW_LINES_OF_CODE: "True"
           SHOW_PROFILE_VIEWS: "False"
           SHOW_PROJECTS: "False"
